[package]
name = "todo"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
crossterm = "0.27.0"
oauth2 = "4.4.2"
serde = "1.0.204"
serde_json = "1.0.120"
thiserror = "1.0.62"
tokio = "1.38.0"
